# Generated by Django 2.2.4 on 2019-12-05 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juegoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='respuesta',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='respuesta', to='juegoApp.Autores'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='autor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='autor', to='juegoApp.Autores'),
        ),
    ]
