# Generated by Django 2.2.4 on 2019-12-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegoApp', '0006_auto_20191205_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='respuesta',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
    ]
